@startuml
!include <C4/C4_Container>
!include <C4/C4_Component>

System_Boundary(anv, "Alfresco Node Vault") {
  Component(anvProxy, "Proxy")
  Component(anvApi, "REST API")
  Component(anvBehaviour, "Behaviour")
  Component(anvJob, "Scheduled job")
  Component(anvVault, "VaultService")
  Component(anvAlfresco, "AlfrescoService")
  ContainerDb(anvMongo, "Mongo DB")
}

note right of [anvProxy]
Intercepts calls to Alfresco
and serves documents from MongoDB
if they are no longer present in Alfresco
end note

System_Boundary(acs, "Alfresco Content Service") {
  ContainerQueue(acsQueue, "Active MQ")
  Component(acsApi, "REST API")
}

Rel_U(anvBehaviour, acsQueue, "uses")
Rel_D(anvProxy, anvApi, "uses")
Rel_R(anvProxy, acsApi, "uses")
Rel_D(anvApi, anvVault, "uses")
Rel_D(anvBehaviour, anvVault, "uses")
Rel_D(anvJob, anvVault, "uses")
Rel_D(anvJob, anvAlfresco, "uses")
BiRel_D(anvVault, anvMongo, "reads/writes")
Rel_R(anvVault, anvAlfresco, "uses")
Rel_R(anvAlfresco, acsApi, "uses")

Component(client, "Client")

Rel_D(client, anvProxy, "uses")
Rel_D(client, anvApi, "uses")
Rel_D(client, acsApi, "uses")

@enduml