services:
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: anv-prometheus
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  grafana:
    build:
      dockerfile: ./grafana/Dockerfile
      context: .
      args:
        GRAFANA_IMAGE: ${GRAFANA_IMAGE}
    container_name: anv-grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - anv-grafana-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  nginx:
    image: ${NGINX_IMAGE}
    container_name: anv-nginx
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  anv-grafana-volume:
    name: grafana-data