services:
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: anv-prometheus
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  loki:
    image: ${LOKI_IMAGE}
    container_name: anv-loki
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./grafana/loki-config.yml:/etc/loki/config.yml
      - anv-loki-volume:/loki
  promtail:
    image: ${PROMTAIL_IMAGE}
    container_name: anv-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./grafana/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - anv-promtail-volume:/tmp
    depends_on:
      - loki
  grafana:
    build:
      dockerfile: ./grafana/Dockerfile
      context: .
      args:
        GRAFANA_IMAGE: ${GRAFANA_IMAGE}
    container_name: anv-grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - anv-grafana-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  nginx:
    image: ${NGINX_IMAGE}
    container_name: anv-nginx
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  anv-grafana-volume:
    name: grafana-data
  anv-loki-volume:
    name: loki-data
  anv-promtail-volume:
    name: promtail-data
