global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'alfresco-node-vault'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['anv-vault:8086']
    basic_auth:
      username: 'admin'
      password: 'admin'