services:
  anv:
    image: anv:latest
    build:
      dockerfile: ../Dockerfile.vault
      context: ./
    environment:
      ALFRESCO_BASE_PATH: http://alfresco:8080
      ACTIVE_MQ_URL: tcp://activemq:61616
      MONGODB_URL: mongodb://mongo:27017
    ports:
      - "8086:8086"
    networks:
      - anv-shared-network
networks:
  anv-shared-network:
    external: true