# prometheus.yml
# https://grafana.com/grafana/dashboards/19004-spring-boot-statistics/
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'alfresco-node-vault'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
    basic_auth:
      username: 'admin'
      password: 'admin'