services:
  localstack:
    build:
      context: ./localstack
      args:
        LOCALSTACK_IMAGE: ${LOCALSTACK_IMAGE}
    container_name: anv-localstack
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'